### ISSUE TITLE
The order of masking and softmax operation

### ISSUE THREAD

**Issue by cfeng16** [lucidrains/memory-compressed-attention#2]
Hi,

In [memory_compressed_attention.py](https://github.com/lucidrains/memory-compressed-attention/blob/master/memory_compressed_attention/memory_compressed_attention.py), I'm wondering if we need to do softmax operation after masking? Btw, if the entry in the mask should be float('-inf') instead of -float('-inf')? If I make something wrong, please correct me.

<img width="493" alt="image" src="https://user-images.githubusercontent.com/61045930/170620613-88c7d795-abfa-416e-8503-9ad3edcb0e4e.png">

Thanks!

**Comment by lucidrains** [comment]
@chlorophyllccc yes you are right! fixed in https://github.com/lucidrains/memory-compressed-attention/commit/a41fd4dfdcc7b63a47a2a09eb485deeda2abe0e0 !

**Comment by cfeng16** [comment]
Thanks for your reply! I'm wondering if in line 78,
<img width="616" alt="image" src="https://user-images.githubusercontent.com/61045930/185525728-778dc017-7e43-4041-9b34-27ad3abe8095.png">
the  -float('-inf') needs to be changed to  float('-inf')? Since in softmax exp(float('-inf')) would be zero (Because it's causal, the later part should be zeroed out) but exp(-float('-inf')) would cause NaN issue.

**Comment by lucidrains** [comment]
@chlorophyllccc oh yes thank you :man_facepalming: i can't believe i wrote this https://github.com/lucidrains/memory-compressed-attention/commit/49d2e7497721f4d6353fe59b4dc636260c627b48
